export const permissions: Record<string, string[]> = {
  ADMIN: [
    "users:read",
    "users:add",
    "users:update",
    "users:delete",
    "users:toggle-activity",
    "years:read",
    "years:add",
    "years:update",
    "years:delete",
    "sections:read",
    "sections:add",
    "sections:update",
    "sections:delete",
    "majors:read",
    "majors:add",
    "majors:update",
    "majors:delete",
    "groups:read",
    "groups:add",
    "groups:update",
    "groups:delete",
    "locations:read",
    "locations:add",
    "locations:update",
    "locations:delete",
    "courses:read",
    "courses:read-one",
    "courses:add",
    "courses:update",
    "courses:delete",
    "course-files:read",
    "course-files:add",
    "course-files:update",
    "course-files:delete",
    "course-files:upload",
    "system-settings:read",
    "system-settings:update",
    "faculity-info:read",
    "faculity-info:update",
    "faqs:read",
    "faqs:add",
    "faqs:update",
    "faqs:delete",
    "blogs:read",
    "blogs:add",
    "blogs:update",
    "blogs:delete",
    "exam-guidelines:read",
    "exam-guidelines:add",
    "exam-guidelines:update",
    "exam-guidelines:delete",
    "marks:read",
    "marks:add",
    "marks:update",
    "marks:delete",
    "files:upload",
    "lectures:read",
    "lectures:add",
    "lectures:update",
    "lectures:delete",
    "announcements:read",
    "announcements:add",
    "announcements:update",
    "announcements:delete",
    "weekly-lectures:read",
    "weekly-lectures:generate",
    "weekly-lectures:publish",
    "weekly-lectures:toggle-cancel",
    "attendance:mark",
    "exams:read",
    "exams:add",
    "exams:update",
    "exams:delete",
    "time-conditioned-items:read",
  ],
  DOCTOR: [
    "course-files:read",
    "course-files:theoretical_and_practical",
    "course-files:add",
    "course-files:update",
    "course-files:delete",
    "course-files:upload",
    // "marks:read",
    // "marks:add",
    // "marks:update",
    // "marks:delete",
    "files:upload",
    // "users:read",
    // "years:read",
    "sections:read",
    "majors:read",
    "groups:read",
    // "courses:read",
    "courses:read-one",
    "my-courses:read",
    // "announcements:read",
    "my-announcements:read",
    "announcements:add",
    "announcements:update",
    "announcements:delete",
    "lectures:read",
    "weekly-lectures:read",
    "weekly-lectures:toggle-cancel",
    // "exams:read",
  ],
  TEACHER: [
    "course-files:read",
    "course-files:practical",
    "course-files:add",
    "course-files:update",
    "course-files:delete",
    "course-files:upload",
    // "marks:read",
    // "marks:add",
    // "marks:update",
    // "marks:delete",
    "files:upload",
    "weekly-lectures:read",
    "weekly-lectures:generate",
    "weekly-lectures:publish",
    "weekly-lectures:toggle-cancel",
    "attendance:mark",
    // "users:read",
    // "years:read",
    "sections:read",
    "majors:read",
    "groups:read",
    // "courses:read",
    "courses:read-one",
    "my-courses:read",
    // "announcements:read",
    "my-announcements:read",
    "announcements:add",
    "announcements:update",
    "announcements:delete",
    "lectures:read",
    "weekly-lectures:read",
    // "exams:read",
  ],
  CONTENT_DE: [
    "faqs:read",
    "faqs:add",
    "faqs:update",
    "faqs:delete",
    "blogs:read",
    "blogs:add",
    "blogs:update",
    "blogs:delete",
    "exam-guidelines:read",
    "exam-guidelines:add",
    "exam-guidelines:update",
    "exam-guidelines:delete",
    "announcements:read",
    "announcements:add",
    "announcements:update",
    "announcements:delete",
  ],
  EXAMS_DE: [
    "exams:read",
    "exams:add",
    "exams:update",
    "exams:delete",
    "marks:read",
    "marks:add",
    "marks:update",
    "marks:delete",
  ],
  LECTURES_SCHEDULE_DE: [
    "years:read",
    "sections:read",
    "majors:read",
    "lectures:read",
    "lectures:add",
    "lectures:update",
    "lectures:delete",
  ],
  MARKS_DE: [],
  STUDENT: [
    "years:read",
    "student-profile:read",
    "student-profile:update",
    "student-profile:change-password",
    "student-profile:upload-picture",
    "locations:read",
    "student-courses:read",
    "course-files:read",
    "system-settings:read",
    "faculity-info:read",
    "faqs:read",
    "blogs:read",
    "exam-guidelines:read",
    "student-marks:read",
    "files:upload",
    "lectures:read",
    "student-announcements:read",
    "weekly-lectures:read",
    "attendance:mark",
    "student-exams:read",
    "time-conditioned-items:read",
    "push-subscriptions:manage",
    "notifications:read",
    "notifications:update",
  ],
};

export type Role = keyof typeof permissions;
